import pandas as pd
import numpy as np

#############################################################################
#### Building Energy Data from NYC Government only primarytype = 'office'####
#############################################################################

#read csv to df
df_all_energy = pd.read_csv('/Users/luchen/Documents/MSUA/2023Spring/Capstone/datasets/Energy_and_Water_Data_Disclosure_for_Local_Law_84_2021__Data_for_Calendar_Year_2020_.csv')
# print(df_all.head())

# all column names
# Property Id, Property Name, Parent Property Id, Parent Property Name, Year Ending, NYC Borough, Block and Lot (BBL), NYC Building Identification Number (BIN), Address 1, City, Postcode, 
# Primary Property Type - Self Selected, Primary Property Type - Portfolio Manager-Calculated, National Median Reference Property Type, List of All Property Use Types at Property, Largest Property Use Type, Largest Property Use Type - Gross Floor Area (ft²), 2nd Largest Property Use Type, 2nd Largest Property Use - Gross Floor Area (ft²), 3rd Largest Property Use Type, 3rd Largest Property Use Type - Gross Floor Area (ft²), 
# Year Built, Construction Status, Number of Buildings, Occupancy, Metered Areas (Energy), Metered Areas (Water), ENERGY STAR Score, National Median ENERGY STAR Score, Target ENERGY STAR Score, Reason(s) for No Score, ENERGY STAR Certification - Year(s) Certified (Score), ENERGY STAR Certification - Eligibility, ENERGY STAR Certification - Last Approval Date, 
# Site EUI (kBtu/ft²), Weather Normalized Site EUI (kBtu/ft²), National Median Site EUI (kBtu/ft²), Site Energy Use (kBtu), Weather Normalized Site Energy Use (kBtu), Weather Normalized Site Electricity Intensity (kWh/ft²), Weather Normalized Site Natural Gas Intensity (therms/ft²), Source EUI (kBtu/ft²), Weather Normalized Source EUI (kBtu/ft²), National Median Source EUI (kBtu/ft²), Source Energy Use (kBtu), Weather Normalized Source Energy Use (kBtu), 
# Fuel Oil #1 Use (kBtu), Fuel Oil #2 Use (kBtu), Fuel Oil #4 Use (kBtu), Fuel Oil #5 & 6 Use (kBtu), Diesel #2 Use (kBtu), Propane Use (kBtu), District Steam Use (kBtu), District Hot Water Use (kBtu), District Chilled Water Use (kBtu), Natural Gas Use (kBtu), Natural Gas Use (therms), 
# Weather Normalized Site Natural Gas Use (therms), Electricity Use - Grid Purchase (kBtu), Electricity Use - Grid Purchase (kWh), Weather Normalized Site Electricity (kWh), Electricity Use - Grid Purchase and Generated from Onsite Renewable Systems (kWh), Electricity Use - Grid Purchase and Generated from Onsite Renewable Systems (kBtu), Electricity Use – Generated from Onsite Renewable Systems and Used Onsite (kWh), Electricity Use – Generated from Onsite Renewable Systems and Used Onsite (kBtu), Electricity Use – Generated from Onsite Renewable Systems (kWh), Electricity Use – Generated from Onsite Renewable Systems and Exported (kWh), 
# Annual Maximum Demand (kW), Annual Maximum Demand (MM/YYYY), Annual Maximum Demand (Meter Name (Meter ID)), Green Power - Onsite (kWh), Green Power - Offsite (kWh), Green Power - Onsite and Offsite (kWh), Total GHG Emissions (Metric Tons CO2e), Direct GHG Emissions (Metric Tons CO2e), Total GHG Emissions Intensity (kgCO2e/ft²), Direct GHG Emissions Intensity (kgCO2e/ft²), Indirect GHG Emissions (Metric Tons CO2e), Net Emissions (Metric Tons CO2e), Indirect GHG Emissions Intensity (kgCO2e/ft²), National Median Total GHG Emissions (Metric Tons CO2e), eGRID Output Emissions Rate (kgCO2e/MBtu), Avoided Emissions - Onsite Green Power (Metric Tons CO2e), Avoided Emissions - Offsite Green Power (Metric Tons CO2e), Avoided Emissions - Onsite and Offsite Green Power (Metric Tons CO2e), 
# Percent of Electricity that is Green Power, Percent of RECs Retained, Percent of Total Electricity Generated from Onsite Renewable Systems, LEED US Project ID, 
# Adult Education - Gross Floor Area (ft²), Ambulatory Surgical Center - Gross Floor Area (ft²), Automobile Dealership - Gross Floor Area (ft²), Bank Branch - Gross Floor Area (ft²), Barracks- Gross Floor Area (ft²), College/University - Gross Floor Area (ft²), Convention Center - Gross Floor Area (ft²), Courthouse - Gross Floor Area (ft²), Data Center - Gross Floor Area (ft²), Data Center - UPS System Redundancy, Data Center - Cooling Equipment Redundancy, Data Center - IT Energy Configuration, Data Center - Energy Estimates Applied, Data Center - UPS Output Meter (kWh), Data Center - PDU Input Meter (kWh), Data Center - PDU Output Meter (kWh), Data Center - IT Equipment Input Meter (kWh), Data Center - IT Site Energy (kWh), Data Center - IT Source Energy (kBtu), Data Center - PUE, Data Center - National Median PUE, Distribution Center - Gross Floor Area (ft²), Enclosed Mall - Gross Floor Area (ft²), Energy/Power Station - Gross Floor Area (ft²), Financial Office - Gross Floor Area (ft²), Financial Office - Number of Computers, Financial Office - Weekly Operating Hours, Financial Office - Number of Workers on Main Shift, Fitness Center/Health Club/Gym - Gross Floor Area (ft²), Food Sales - Gross Floor Area (ft²), Food Service - Gross Floor Area (ft²), Hospital (General Medical & Surgical)- Full Time Equivalent (FTE) Workers, Hospital (General Medical & Surgical) - Gross Floor Area (ft²), Hospital (General Medical & Surgical) - Laboratory, Hospital (General Medical & Surgical) - Licensed Bed Capacity, Hospital (General Medical & Surgical) - Number of MRI Machines, Hospital (General Medical & Surgical) - MRI Density (Number per 1,000 sq ft), Hospital (General Medical & Surgical) - Number of Staffed Beds, Hospital (General Medical & Surgical) - Staffed Bed Density (Number per 1,000 sq ft), Hospital (General Medical & Surgical) - Number of Workers on Main Shift, Hospital (General Medical & Surgical) - Number of Workers on Main Shift Density (Number per 1,000 sq ft), Hospital (General Medical & Surgical) - Percent That Can Be Cooled, Hospital (General Medical & Surgical) - Percent That Can Be Heated, Medical Office - Gross Floor Area (ft²), Medical Office - Number of Computers, Medical Office - Number of MRI Machines, Medical Office - Number of Workers on Main Shift, Medical Office - Percent That Can Be Cooled, Medical Office - Percent That Can Be Heated, Medical Office - Weekly Operating Hours, Outpatient Rehabilitation/Physical Therapy - Gross Floor Area (ft²), Urgent Care/Clinic/Other Outpatient - Gross Floor Area (ft²), Hotel - Gross Floor Area (ft²), 
# Hotel - Gym/fitness  Center Floor Area (ft²), K-12 School - Gross Floor Area (ft²), Pre-school/Daycare - Gross Floor Area (ft²), Laboratory - Gross Floor Area (ft²), Mailing Center/Post Office - Gross Floor Area (ft²), Movie Theater - Gross Floor Area (ft²), Manufacturing/Industrial Plant - Gross Floor Area (ft²), Multifamily Housing - Government Subsidized Housing, Multifamily Housing - Gross Floor Area (ft²), Multifamily Housing - Number of Bedrooms, Multifamily Housing - Number of Bedrooms Density (Number per 1,000 sq ft), Multifamily Housing - Number of Laundry Hookups in All Units, Multifamily Housing - Number of Laundry Hookups in Common Area(s), Multifamily Housing - Number of Residential Living Units in a High-Rise Building (10 or more Stories), Multifamily Housing - Total Number of Residential Living Units, Multifamily Housing - Total Number of Residential Living Units Density (Number per 1,000 sq ft), Multifamily Housing - Number of Residential Living Units in a High-Rise Building Density (Number per 1,000 sq ft), Multifamily Housing - Number of Residential Living Units in a Mid-Rise Building (5-9 Stories), Multifamily Housing - Number of Residential Living Units in a Mid-Rise Building Density (Number per 1,000 sq ft), Multifamily Housing - Percent That Can Be Cooled, Multifamily Housing - Percent That Can Be Heated, Multifamily Housing - Resident Population Type, Residence Hall/Dormitory - Gross Floor Area (ft²), Non-Refrigerated Warehouse - Gross Floor Area (ft²), Office - Gross Floor Area (ft²), Office - Number of Computers, Office - Number of Workers on Main Shift, Office - Percent That Can Be Cooled, Office - Percent That Can Be Heated, Office - Weekly Operating Hours, Office - Worker Density (Number per 1,000 sq ft), Other - Gross Floor Area (ft²), Museum - Gross Floor Area (ft²), 
# Performing Arts - Gross Floor Area (ft²), Parking - Gross Floor Area (ft²), Parking - Completely Enclosed Parking Garage Size (ft²), Parking - Open Parking Lot Size (ft²), Parking - Partially Enclosed Parking Garage Size (ft²), Refrigerated Warehouse - Gross Floor Area (ft²), Restaurant - Gross Floor Area (ft²), Restaurant - Weekly Operating Hours, Restaurant - Worker Density (Number per 1,000 sq ft), Retail Store - Gross Floor Area (ft²), Retail Store - Number of Walk-in Refrigeration/Freezer Units, Retail Store - Number of Open or Closed Refrigeration/Freezer Units, Self-Storage Facility - Gross Floor Area (ft²), Senior Living Community - Gross Floor Area (ft²), Senior Living Community - Living Unit Density (Number per 1,000 sq ft), Social/Meeting Hall - Gross Floor Area (ft²), Supermarket/Grocery - Gross Floor Area (ft²), 
# Supermarket/Grocery - Number of Open or Closed Refrigeration/Freezer Units, Supermarket/Grocery - Number of Walk-in Refrigeration/Freezer Units, Wholesale Club/Supercenter- Gross Floor Area (ft²), Wholesale Club/Supercenter- Exterior Entrance to the Public, Wastewater Treatment Plant - Gross Floor Area (ft²), Worship Facility - Gross Floor Area (ft²), Estimated Data Flag - Electricity (Grid Purchase), Estimated Data Flag - Natural Gas, Estimated Data Flag - Fuel Oil (No. 1), Estimated Data Flag - Fuel Oil (No. 2), Estimated Data Flag - Fuel Oil (No. 4), Estimated Data Flag - Fuel Oil (No. 5 and No. 6), Estimated Data Flag - District Steam, Estimated Data Flag - Municipally Supplied Potable Water: Mixed Indoor/Outdoor Use, Estimated Values - Energy, Estimated Values - Water, Alert - Data Center Issue (with Estimates, 
# IT Configuration, or IT Meter), Alert - Energy Meter has less than 12 full calendar months of data, Alert - Energy Meter has gaps, Alert - Energy Meter has overlaps, Alert - Energy - No meters selected for metrics, Alert - Energy Meter has single entry more than 65 days, Alert - Water Meter has less than 12 full calendar months of data, Alert - Property has no uses, Default Values, Temporary Values, Property GFA - Self-Reported (ft²), Property GFA - Calculated (Buildings and Parking) (ft²), Property GFA - Calculated (Buildings) (ft²), Property GFA - Calculated (Parking) (ft²), Water Use (All Water Sources) (kgal), Indoor Water Use (All Water Sources) (kgal), Outdoor Water Use (All Water Sources) (kgal), Municipally Supplied Potable Water - Mixed Indoor/Outdoor Use (kgal), Municipally Supplied Potable Water - Total Use (All Meter Types) (kgal), Municipally Supplied Potable Water - Indoor Use (kgal), Municipally Supplied Potable Water - Outdoor Use (kgal), 
# Third Party Certification, Third Party Certification Date Anticipated, Third Party Certification Date Achieved, Last Modified Date - Property, Last Modified Date - Electric Meters, Last Modified Date - Gas Meters, Last Modified Date - Non-Electric Non-Gas Energy Meters, Last Modified Date - Water Meters, Last Modified Date - Property Use, Number of Active Energy Meters - Total, Number of Active Energy Meters - Used to Compute Metrics, Number of Active Energy Meters - Not Used to Compute Metrics, Number of Active IT Meters, Generation Date, Release Date, Borough, Community Board, Council District, Census Tract, NTA, Longitude, Latitude

# filter - useful columns
cols_to_drop_energy = df_all_energy.iloc[:, 89:166].columns.tolist() + df_all_energy.columns[[2,3,8,170,171,172,239,240]].tolist() + df_all_energy.iloc[:, 187:226].columns.tolist() + df_all_energy.iloc[:, 180:216].columns.tolist() + df_all_energy.iloc[:, 232:238].columns.tolist()
df_energy = df_all_energy.drop(columns=cols_to_drop_energy)
# num_rows, num_cols = df_all.shape
# print(f"The DataFrame has {num_rows} rows and {num_cols} columns.")

# num_rows, num_cols = df.shape
# print(f"The DataFrame has {num_rows} rows and {num_cols} columns.")
df_energy.to_csv('/Users/luchen/Documents/MSUA/2023Spring/Capstone/datasets/nyc_energy.csv', index=False)


#########################################
#### NSI Data only in NYC 5 boroughs ####
#########################################

#read csv to df
df_all = pd.read_csv('/Users/luchen/Documents/MSUA/2023Spring/Capstone/datasets/nsi_nystate.csv')
# print(df_all.head())
# num_rows, num_cols = df_all.shape
# print(f"The DataFrame has {num_rows} rows and {num_cols} columns.")

#cut west
df = df_all[df_all['x'] > -74.6949225]
# print(df.head())
# num_rows1, num_cols1 = df.shape
# print(f"The DataFrame has {num_rows1} rows and {num_cols1} columns.")

#cut up
df2 = df[df['y'] < 40.9275715]
print(df2.head())
num_rows, num_cols = df2.shape
print(f"The DataFrame has {num_rows} rows and {num_cols} columns.")

#csv
df2.to_csv('/Users/luchen/Documents/MSUA/2023Spring/Capstone/datasets/nyc_nsi_rough.csv', index=False)

